### ISSUE TITLE
Source code for games

### ISSUE THREAD

**Issue by rnovacek** [Pajenicko/Picopad#13]
Is there a source code available for the games? For example Train (vlak)? I would like to customize them for a gaming console I made.

I couldn't find them in the repo but maybe I'm just blind...

**Comment by Neolker** [comment]
Sure: https://github.com/Panda381/PicoLibSDK/blob/4852082b90e33b8759f0e56dbaed7ea95bc6aa86/PicoPad/GAME/TRAIN/src/main.cpp

**Comment by rnovacek** [comment]
That's perfect, thank you!
